### ISSUE TITLE
dashDotDot not working as linestyle

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#105]
Trying to set dashDotDot results in
```
ValueError: 'dashdotdotted' is not a valid value for ls; supported values are 
'-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'
```
According to discussion and specification this is a valid linestyle. Also the list `'-', '--', '-.', ':', 'None', ' ', '', 'solid', 'dashed', 'dashdot', 'dotted'` should be `none`, `solid`, `dash`, `dot`, `dashDot`, `dashDotDot`

**Comment by fbergmann** [comment]
it is working on the c++ level,  so i'm not sure where this line is coming from? Are you sure it is form libsedml?

**Comment by matthiaskoenig** [comment]
This has been resolved. Had nothing to do with the library.
