### ISSUE TITLE
Question: how can a document be validated on writing?

### ISSUE THREAD

**Issue by jonrkarr** [fbergmann/libSEDML#138]
Here's a brief snippet to create a document with a report that's missing an id:
```python
import libsedml
doc = libsedml.SedDocument()
report = doc.createReport()
libsedml.writeSedMLToFile(doc, 'test.sedml')
log = doc.getErrorLog()
print(log.getNumErrors())
```

What's the syntax to validate the document on writing? Can the document be validated in memory before writing to a file?

**Comment by matthiaskoenig** [comment]
You could just write to a string first.
```python
import libsedml
doc = libsedml.SedDocument()
report = doc.createReport()
sedml_str = libsedml.writeSedMLToString(doc)
log = doc.getErrorLog()
print(log.getNumErrors())
if not log.getNumFailsWithSeverity(libsedml.LIBSEDML_SEV_ERROR) and not log.getNumFailsWithSeverity(libsedml.LIBSEDML_SEV_FATAL):
    with open('test.sedml', 'w') as f_out:
        f_out.write(sedml_str)
```

**Comment by jonrkarr** [comment]
That doesn't work. The number of errors is zero at that point.

**Comment by jonrkarr** [comment]
Does a separate method need to be called, or is validation only applied during reading?

**Comment by fbergmann** [comment]
Indeed, all validation logic so far is only applied on reading, so a validation function could look like: 
    
    sedml = libsedml.writeSedMLToString(doc)
    temp_doc = libsedml.readSedMLFromString(sedml)
    log = temp_doc.getErrorLog()
    print(log.getNumErrors())
    if not log.getNumFailsWithSeverity(libsedml.LIBSEDML_SEV_ERROR) and not log.getNumFailsWithSeverity(libsedml.LIBSEDML_SEV_FATAL):
        with open('test.sedml', 'w') as f_out:
            f_out.write(sedml_str)

**Comment by jonrkarr** [comment]
Thanks. I know I can use reading for validation. I thought there might be a more direct route.
