### ISSUE TITLE
New release with latest changes

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#139]
I wanted to implement the latest changes. Would it be possible to
- add the reverse attribute: https://github.com/fbergmann/libSEDML/issues/127
- add the symbol on ComputeChange and ChangeAttribute: https://github.com/fbergmann/libSEDML/issues/122

and make a new release.

Best Matthias

**Comment by fbergmann** [comment]
sure, i'll try to get it out today

**Comment by fbergmann** [comment]
@matthiaskoenig new release tagged and on pypi

**Comment by matthiaskoenig** [comment]
This is great. Thanks.
