### ISSUE TITLE
Remove Fill.secondColor which isn't part of SED-ML

### ISSUE THREAD

**Issue by jonrkarr** [fbergmann/libSEDML#159]
The Fill class has an attribute `secondColor` which isn't documented in the SED-ML specifications. I think this should be aligned with SED-ML, either by removing this from libSED-ML or adding it to SED-ML.

https://github.com/fbergmann/libSEDML/blob/39bdb7c25120ba80c6d10da3b9702d9a8d9e52f5/dev/sedml.xml#L437

**Comment by luciansmith** [comment]
Ah, this was mostly handled with https://github.com/fbergmann/libSEDML/pull/131 but I missed that one.  Will update.
