### ISSUE TITLE
create_sedml can't find numl

### ISSUE THREAD

**Issue by luciansmith** [fbergmann/libSEDML#16]
I told CMake about libnuml, and most things found it, but create_sedml didn't (on windows):

8>..\..\..\examples\c++\create_sedml.cpp(40): fatal error C1083: Cannot open include file: 'numl/NUMLTypes.h': No such file or directory

**Comment by luciansmith** [comment]
Also for the python bindings:

2>C:\Users\Lucian\Desktop\libSEDML\bindings\python\..\swig\libsedml.i(468): error : Unable to find 'numl\common\extern.h'

**Comment by fbergmann** [comment]
thanks for letting me know ... odd that this did not occur for me, maybe because I keep files in one dependency folder where it would pick up libsbml and libnuml at the same time.

**Comment by luciansmith** [comment]
I just updated, and am still getting the problem for the python bindings:

3>C:\Users\Lucian\Desktop\libSEDML\bindings\python\..\swig\libsedml.i(469): error : Unable to find 'numl\common\extern.h'

But the create_sedml issue has been fixed.

**Comment by fbergmann** [comment]
all bindings now include the numl directory
