### ISSUE TITLE
No CMake config files get generated?

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#162]
It looks like the [`level1-version4`](https://github.com/fbergmann/libSEDML/tree/level1-version4) branch doesn't generate any CMake config files while the [`master`](https://github.com/fbergmann/libSEDML/tree/master) branch does. Am I correct or did I miss something? Either way, it would be good to generate CMake config files or it would be nice if you could tell me how to ensure that they get generated.

**Comment by fbergmann** [comment]
Thanks for noticing, strange that those got lost along the way. I'll make a new version with them in it.

**Comment by fbergmann** [comment]
this has been resolved
