### ISSUE TITLE
The libSEDML python validator doesn't accept empty lists of variables / parameters in SetValue.

### ISSUE THREAD

**Issue by danv61** [fbergmann/libSEDML#165]
I receive the message: "...is not a valid SED-ML file: (20103 [Error]) No empty lists, 
listOfVariables cannot be empty"

Although sedml L1V3 specifications state that empty lists of variables / parameters are legal:
"2.1.7.7 listOfVariables ... The listOfVariables is optional and may contain zero to many variables."

Same for listOfParameters

**Comment by fbergmann** [comment]
thanks for letting me know

**Comment by fbergmann** [comment]
if everything went as planned, there is a new pypi version released now that solves the issue, please let me know.
