### ISSUE TITLE
Kisao terms as ints?

### ISSUE THREAD

**Issue by luciansmith** [fbergmann/libSEDML#18]
It would be nice if there were kisao term set/get options that returned them by int, instead of by string.  In fact, if the string versions went away entirely, I would not miss them.

**Comment by fbergmann** [comment]
I'm uncomfortable yanking them entirely. But if ints are more helpful for you I will add functions

    int getKisaoIDasInt() const;
    setKisaoID(int)

hope that'll help

**Comment by luciansmith** [comment]
That'd be great!  Thank you.
