### ISSUE TITLE
Create no timestamp when creating SEDML

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#24]
No timestamp should be inserted when writing SEDML

see also https://sourceforge.net/p/phrasedml/tickets/16/

I create a large amount of files on the fly with antimony and phrasedml which are managed in repositories. Due to the timestamps every commit has 100s of files, because all the changes in the timestamps are part of the commits. Even if nothing changed in the files.

I also wrote timestamps & model histories in my files before, but it creates more problems than it is useful. Having the files in a repository is a much better solution and one can always access the exact time of creation/modification. 
If one wants timestamps in the files one can write a model history/annotation which contains the information, but it should not be inserted by default.

**Comment by fbergmann** [comment]
libSEDML does not write timestamps into the files without the application using libSEDML calling the functions to do so ... so there is not much i can change at this end.

**Comment by matthiaskoenig** [comment]
Okay. Moving on to libSBML ;) Sorry for filing this here.
Seems like the XMLOutputStream.writeComment() of libSBML is the problem.
Can be closed here.

**Comment by luciansmith** [comment]
The functions in question are simply:

  SedWriter sw;
  sw.setProgramName("phraSED-ML");
  sw.setProgramVersion(LIBPHRASEDML_VERSION_STRING);
  sw.writeSedML(m_sedml, stream);

Which do not mention the timestamp--if you put in the program name and version, you get the timestamp automatically.  It's the timestamp in particular that would be nice if you could suppress.

**Comment by matthiaskoenig** [comment]
With the new XMLOutput methods in libsbml this issue is resolved.
