### ISSUE TITLE
Cannot build with namespace-enabled libSBML

### ISSUE THREAD

**Issue by 0u812** [fbergmann/libSEDML#26]
I tried building libsedml against libsbml experimental (rev. 23207, last changed 23180) with namespaces enabled. I get the following error, which I believe is due to the fact that namespaces are enabled in this build of libsbml:
```
Building CXX object sedml/CMakeFiles/sedml.dir/SedChange.cpp.o
In file included from /home/poltergeist/devel/src/libsedml/sedml/SedChange.cpp:38:
In file included from /home/poltergeist/devel/src/libsedml/sedml/../sedml/SedTypes.h:75:
In file included from /home/poltergeist/devel/src/libsedml/sedml/../sedml/SedDocument.h:54:
In file included from /home/poltergeist/devel/src/libsedml/sedml/../sedml/SedDataDescription.h:54:
In file included from /home/poltergeist/devel/install/libnuml/include/numl/DimensionDescription.h:37:
In file included from /home/poltergeist/devel/install/libnuml/include/numl/AtomicDescription.h:32:
/home/poltergeist/devel/install/libnuml/include/numl/NMBase.h:218:11: error: reference to 'XMLNamespaces' is ambiguous
  virtual XMLNamespaces* getNamespaces() const ;
          ^
/home/poltergeist/devel/install/libnuml/include/numl/NMBase.h:58:7: note: candidate found by name lookup is 'XMLNamespaces'
class XMLNamespaces;
      ^
/home/poltergeist/devel/src/libsedml/sedml/../sedml/SedBase.h:166:7: note: candidate found by name lookup is 'libsbml::XMLNamespaces'
class XMLNamespaces;
```
There are many similar errors in the build output that I didn't show for brevity.

**Comment by 0u812** [comment]
I just managed to build it against the same checkout of libsbml compiled without namespaces, so I guess that confirms the problem. Building two versions of libsbml for my project is a bit excessive so it would be great if libsedml could support libsbml namespaces.

**Comment by fbergmann** [comment]
From the message that you posted above the issue is with the NUML library. It will still be me that will have to fix it, but it is not this project :) 

If you don't use NUML right now, you could take the last release. That one was tested to be sure to work with libSBML and c++ namespaces.

**Comment by 0u812** [comment]
Whoops sorry! I'll move this issue to that project.
