### ISSUE TITLE
libSEDML Java bindings not building with latest libnuml

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#27]
Hi Frank,

I tried to update libsedml to the latest commit. With the latest changes in libnuml the JAVA swig bindings are not building any more.

I get the following errors
```
[ 81%] Built target sedml-static
Scanning dependencies of target binding_java_swig
[ 82%] Swig Java source
/usr/local/include/numl/NUMLNamespaces.h:162: Error: Syntax error in input(3).
make[2]: *** [bindings/java/libsedml_wrap.cpp] Error 1
make[1]: *** [bindings/java/CMakeFiles/binding_java_swig.dir/all] Error 2
make: *** [all] Error 2
```

The full log and build script I am using are attached.
I am on Ubuntu 14.04 LTS 64bit.

[libsedml_logs.zip](https://github.com/fbergmann/libSEDML/files/238229/libsedml_logs.zip)

Matthias

**Comment by fbergmann** [comment]
thanks ... should be fixed with the latest commit.

**Comment by matthiaskoenig** [comment]
is fixed. thanks a lot.
