### ISSUE TITLE
Issue with Python binding

### ISSUE THREAD

**Issue by kirichoi** [fbergmann/libSEDML#29]
I get following error when I try to build Python bindings for libSEDML.

Error   11  error LNK2019: unresolved external symbol "public: __thiscall NUMLConstructorException::NUMLConstructorException(void)" (??0NUMLConstructorException@@QAE@XZ) referenced in function __wrap_new_NUMLConstructorException    C:\Lib\libSEDML-0.4.1\build\bindings\python\libsedml_wrap.obj   binding_python_lib

It seems like it has something to do with linking. Any ideas?
I am working on Windows 7 using VS2013 with SWIG 3.0.10.

**Comment by fbergmann** [comment]
Hello Kiri, 

the issue is that the new version of libSEDML depends on libNUML so it can support the data proposal. 

https://github.com/NuML/NuML/tree/master/libnuml

best
Frank
