### ISSUE TITLE
C++ namespace issues building against libNuML w/out namespaces enabled

### ISSUE THREAD

**Issue by nickerso** [fbergmann/libSEDML#32]
I think there are some problems when trying to build a namespace enabled libSEDML against libNuML (either with or without the namespaces enabled). Quick investigation looks like the problem might be the `DimensionDescription` forward declaration in `sedmlfwd.h` being wrapped with the `LIBSEDML_CPP_NAMESPACE_BEGIN/END` which puts it into the libsedml namespace. 

Turning off namespaces in both libSEDML and libNuML gets things building.

**Comment by nickerso** [comment]
0775ab9 lets me build libSEDML with namespaces enabled and namespaces disabled in libNuML. If I try enabling namespaces in libNuML there are unresolved symbols when linking the example applications.

**Comment by fbergmann** [comment]
thanks that looks fine to me ... could I ask you to make a pull request? And I would assume that the example applications just will have to include some line like that. I'm still mostly offline this week and likely won't get to it until the 14th.
