### ISSUE TITLE
Build fails (does not use correct libSBML path) on Mac OS X

### ISSUE THREAD

**Issue by 0u812** [fbergmann/libSEDML#35]
The build system appears to be looking for `-lsbml` when linking instead of the absolute path to the library. Also, I'm passing `-DLIBSBML_STATIC=ON` but CMake doesn't appear to be picking up on it.

Here is my command line. I'm also setting `CMAKE_PREFIX_PATH` to include `/path/to/libsbml/lib/cmake` (not shown).
```
cmake -G"Xcode" -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_INSTALL_PREFIX=/Users/phantom/devel/install/libsedml-osx-10.9 -DLIBSBML_LIBRARY=/Users/phantom/devel/install/libsbml-experimental-osx-10.9/lib/libsbml-static.a -DLIBSBML_INCLUDE_DIR=/Users/phantom/devel/install/libsbml-experimental-osx-10.9/include -DLIBSBML_STATIC=ON -DEXTRA_LIBS='xml2;bz2;z;iconv' -DWITH_PYTHON=OFF -DLIBNUML_LIBRARY=/Users/phantom/devel/install/libnuml-osx-10.9/lib/libnuml-static.a -DLIBNUML_INCLUDE_DIR=/Users/phantom/devel/install/libnuml-osx-10.9/include /Users/phantom/devel/src/libsedml
```

Here is an example linker error:
```
Ld /Users/phantom/devel/build/libsedml-osx-10.9/sedml/Release/libsedml.0.4.2.dylib normal x86_64
    cd /Users/phantom/devel/src/libsedml
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -L/Users/phantom/devel/build/libsedml-osx-10.9/sedml/Release -F/Users/phantom/devel/build/libsedml-osx-10.9/sedml/Release -filelist /Users/phantom/devel/build/libsedml-osx-10.9/sedml/libsedml.build/Release/sedml.build/Objects-normal/x86_64/sedml.0.4.2.LinkFileList -install_name /libsedml.0.4.2.dylib -mmacosx-version-min=10.9 -dynamiclib -Wl,-headerpad_max_install_names -install_name /Users/phantom/devel/build/libsedml-osx-10.9/sedml/Release/libsedml.0.dylib -lsbml -lnuml -lxml2 -lbz2 -lz -liconv -single_module -current_version 0.4.2 -Xlinker -dependency_info -Xlinker /Users/phantom/devel/build/libsedml-osx-10.9/sedml/libsedml.build/Release/sedml.build/Objects-normal/x86_64/sedml.0.4.2_dependency_info.dat -o /Users/phantom/devel/build/libsedml-osx-10.9/sedml/Release/libsedml.0.4.2.dylib
ld: library not found for -lsbml
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm using libSBML experimental rev 23757 FWIW.

**Comment by fbergmann** [comment]
Hello Kyle, 

is that from a complete new build? After the request to allow the use of the cmake export modules, those export targets will be imported as found. In fact it should have picked up a sbml-static library first. I've applied the same change to libNUML as well, so it could be that the imported target from the NUML build was linked against a static libSBML, and so when that target is imported, the static library shows up. 

Could you please attach your cmakecache.txt file from the build directory? I unfortunately no longer have a mac for building available at this point so i can't try it out myself. 

thank you
Frank

**Comment by 0u812** [comment]
Hi Frank,

Thanks so much for your response. It is indeed from a fresh build. I checked out the latest libSEDML (e4e6e6956649ce180cdfd70015912f2f97f81720) NuML, (NuML/NuML@d3d12129752e62ed12a4d343c72a3773ec97c026) and experimental libSBML (revision mentioned in last post).


I think it is possible that the CMake script is importing the sbml-static export target, but it isn't using it during linking. For example, if I fail to set `CMAKE_PREFIX_PATH` before running CMake, it fails with this error:
```
CMake Error at CMakeLists.txt:311 (find_package):
  Could not find a package configuration file provided by "sbml-static" with
  any of the following names:

    sbml-staticConfig.cmake
    sbml-static-config.cmake

  Add the installation prefix of "sbml-static" to CMAKE_PREFIX_PATH or set
  "sbml-static_DIR" to a directory containing one of the above files.  If
  "sbml-static" provides a separate development package or SDK, be sure it
  has been installed.
```

I think that the problem may be related to choosing `sbml` vs `sbml-static` depending on the value of `LIBSBML_STATIC`. I think `LIBSBML_LIBRARY` is getting set to `sbml` [here](https://github.com/fbergmann/libSEDML/blob/master/CMakeLists.txt#L290). Then libsedml is linking against `LIBSBML_LIBRARY` (which is set to `sbml`) [here](https://github.com/fbergmann/libSEDML/blob/master/sedml/CMakeLists.txt#L179):
```
target_link_libraries(${LIBSEDML_LIBRARY} ${LIBSBML_LIBRARY} ${LIBNUML_LIBRARY} ${EXTRA_LIBS})
```
However, if I change this line to:
```
target_link_libraries(${LIBSEDML_LIBRARY} ${LIBSBML_LIBRARY}-static ${LIBNUML_LIBRARY}-static ${EXTRA_LIBS})
```
then libsedml compiles. Of course, this should be protected with an `if(LIBSBML_STATIC)` or something.

I'd be happy to test any changes on my Mac for you. Here is my original (failing) CMakeCache.txt file:
[CMakeCache.txt](https://github.com/fbergmann/libSEDML/files/685818/CMakeCache.txt)

**Comment by 0u812** [comment]
Sounds great! Thanks for your help.

**Comment by fbergmann** [comment]
I have made now several improvements to how libsbml and libnuml are detected. It will now work with both the config files as well as the include dir / library setup.
