### ISSUE TITLE
error when compiling java bindings

### ISSUE THREAD

**Issue by FFroehlich** [fbergmann/libSEDML#38]
Disclaimer: I modified the CMakeLists.txt to use find_library/find_path, which were commented out, instead of find_package as I could not find the appropriate cmake files in my libSBML installiation an thus not pass an appropriate CMAKE_PREFIX_PATH. But, I hope this does not lead to the error that I encounter.

To build sedml I used the following command for cmake 

```
cmake .. -DEXTRA_LIBS='xml2;bz2;z;iconv'  -DLIBSBML_LIBRARY='/usr/local/lib/libsbml.dylib' -DLIBSBML_INCLUDE_DIR='/usr/local/include/' -DLIBNUML_LIBRARY='/usr/local/lib/libnuml.dylib' -DLIBNUML_INCLUDE_DIR='/usr/local/include/' -DWITH_JAVA=ON
```

When I subsequently call `make`, the sedml and sedml-static targets build fine, but for the binding_java_swig I encounter the following error: 

```
Scanning dependencies of target binding_java_swig
[ 95%] Swig Java source
/Users/F.Froehlich/Documents/MATLAB/libSEDML/bindings/java/../../sedml/common/sedmlfwd.h:353: Error: Syntax error in input(1).
make[2]: *** [bindings/java/libsedml_wrap.cpp] Error 1
make[1]: *** [bindings/java/CMakeFiles/binding_java_swig.dir/all] Error 2
```

When I compile everything without java bindings compilation works fine.

**Comment by fbergmann** [comment]
thanks for letting me know, soon there will be an official libSBML release that uses the package mechanism, but I am looking into dynamically switching between the two ways of resolving the dependency. 

In the meantime I have committed a fix that should resolve the actual error message you were getting.

**Comment by FFroehlich** [comment]
great! thanks for the quick fix! the compilation works for me now!
