### ISSUE TITLE
python 3.5 language bindings installed despite py 2.7 being default

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#41]
Before when building libsedml with python bindings the python 2.7 version was installed, now suddenly the python 3.5 version is installed, despite 2.7 being the default system version

mkoenig@core1:~$ python --version
Python 2.7.12

```
-- Installing: /usr/local/lib/python3.5/site-packages/libsedml/_libsedml.so
-- Installing: /usr/local/lib/python3.5/site-packages/libsedml.pth
-- Installing: /usr/local/lib/python3.5/site-packages/libsedml/libsedml.py
```
libsedml should install the language bindings for the system version of python.

I could fix this by providing the following build option
```
-DPYTHON_EXECUTABLE="/usr/bin/python"
```
but by default the system version of python should be used.

**Comment by fbergmann** [comment]
I'm just using the default that is returned by the cmake module find python interpreter. And that seems to have returned ```https://github.com/fbergmann/libSEDML/issues/40``` for you the python3.5 executable.  I certainly do not prefer a python 3x version to a python 2x version. 

All I do is to include: 

```
include(FindPythonLibs)
include(FindPythonInterp)

```

**Comment by matthiaskoenig** [comment]
Okay, so this is clearly a cmake issue.

Not sure if you should do the 2 includes in the opposite order: 

https://cmake.org/cmake/help/v3.5/module/FindPythonInterp.html
If calling both find_package(PythonInterp) and find_package(PythonLibs), call find_package(PythonInterp) first to get the currently active Python version by default with a consistent version of PYTHON_LIBRARIES.

I could imagine that you have to find the active interpreter first before finding the libs, this could explain why 3.5 is used instead of 2.7.

**Comment by matthiaskoenig** [comment]
I see the same behavior with libnuml and libcombine, all install now the py 3.5 version instead the 2.7.
Probably due to a recent change in behavior in cmake.

**Comment by matthiaskoenig** [comment]
Just an update. 
It is necessary to set all python information manually. The same for libnuml and libcombine, it is not sufficient to only provide the executable, otherwise in all cases the 3.5 versions are discovered.

```
-DPYTHON_EXECUTABLE="/usr/bin/python" -DPYTHON_INCLUDE_DIR="/usr/include/python2.7" -DPYTHON_LIBRARY="/usr/lib/x86_64-linux-gnu/libpython2.7.so"
```
#42 was a result of having a wrong combination of executables and python library.

**Comment by matthiaskoenig** [comment]
I just looked at antimony & phrasedml where I don't have the issue.
Lucian is doing the following in the CMakeLists.txt for the python bindings which is working

```
#include(FindPythonLibs)
#include(FindPythonInterp)
find_package(PythonInterp)
find_package(PythonLibs)
```

**Comment by fbergmann** [comment]
the issue i had with that is that sometimes the wrong library would be selected in that case. Can you try the patch i just committed? thanks

**Comment by matthiaskoenig** [comment]
Yes. This works. Thanks for this.

Is it possible to patch
* `libnuml`
* `libcombine`

in the same way?

**Comment by fbergmann** [comment]
done .. thanks!
