### ISSUE TITLE
Unable to read SED-ML file with csymbol definitionURL="http://sed-ml.org/#max"

### ISSUE THREAD

**Issue by 0u812** [fbergmann/libSEDML#44]
Hi Frank,
I'm trying to read the SED-ML from your Combine archive example published with your paper [here](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-014-0369-z). It is the SED-ML included in the first supplementary file (also attached for reference). The problem seems to be caused by the `http://sed-ml.org/#max` csymbol definition. Here is the error output:

```
In SBML Level 2, the only values permitted for 'definitionURL' on a <csymbol> element are "http://www.sbml.org/sbml/symbols/time" and "http://www.sbml.org/sbml/symbols/delay". SBML Level 3 added "http://www.sbml.org/sbml/symbols/avogadro". SBML Level 3 Version 2 added "http://www.sbml.org/sbml/symbols/rateOf"
Reference: L3V2 Section 3.4.6
 The <csymbol> definitionURL 'http://sed-ml.org/#max' is not allowed for this level and version of SBML.
```

I am using libSEDML 0.4.2 built against libSBML 5.14.1 experimental from svn. I'm using the Python bindings.

[repressilator-sedml.xml.txt](https://github.com/fbergmann/libSEDML/files/836988/repressilator-sedml.xml.txt)

**Comment by fbergmann** [comment]
Hello Kyle, 

this error is obviously coming from libSBML, so it would seem like a new validation rule was added recently for this. Can you send me the CMakeCache.txt file that you used to compile libSBML? It would be good to know whether you used the new ASTNode implementation, or the old one. 

I will also let the team know about this ... 

cheers
Frank

**Comment by 0u812** [comment]
Thanks for your reply! Here is the CMakeCache.txt. I'm on revision r23826 of the experimental branch of libSBML. I am not currently using `LIBSBML_USE_LEGACY_MATH`, but I can give that a shot.
[CMakeCache.txt](https://github.com/fbergmann/libSEDML/files/839015/CMakeCache.txt)

**Comment by 0u812** [comment]
Unfortunately, trying to open the same file with `LIBSBML_USE_LEGACY_MATH` enabled results in a segmentation fault.

**Comment by fbergmann** [comment]
Hello Kyle, please try the libSBML repo from today, we fixed this one earlier in the day ...

**Comment by 0u812** [comment]
Thanks so much! Now I am able to import the file with `LIBSBML_USE_LEGACY_MATH` enabled.

**Comment by 0u812** [comment]
Hi Frank, I was just checking if this csymbol issue still requires legacy math enabled in libsbml. In Tellurium, we're currently using legacy math all the way through, but ideally we would like to switch it off at some point in the future:)

**Comment by fbergmann** [comment]
Hello Kyle, I've verified that the error is no longer being issued. However, currently it seems that libNuml will fail if libsbml is used without namespaces and arrays enabled.

**Comment by 0u812** [comment]
Thanks Frank! It sounds like enabling namespaces in libsbml, libsedml, and libnuml is a workable solution, correct?

**Comment by fbergmann** [comment]
Indeed, that sames the safest approach ... and of course to remain careful with the import order so that the correct symbols are available at all time
