### ISSUE TITLE
Specifying logX and logY for plot2D

### ISSUE THREAD

**Issue by 0u812** [fbergmann/libSEDML#47]
Hi Frank,

Relatively minor issue here. I was trying to read Combine archives exported by [JWS Online](http://jjj.biochem.sun.ac.za/). It appears to use the as yet unreleased version 3 of SED-ML. When I try to read their SED-ML, libSEDML complains that `plot2D` is missing `logX` and `logY` attributes (the child curves all have these set, but apparently `plot2D` requires it as well). If I simply add the missing `logX` and `logY` elements, then everything is fine.

The reason I'm posting this here is that the SED-ML Web Tools seem to work either way (with or without the `logX`/`logY` attributes). Do the web tools use the C# SED-ML library? If so, it looks like this might be a small discrepancy between the C#/C++ implementations.

[Here](https://drive.google.com/file/d/0B3aYYo6rNYZhYnQzaUhpWFBHZDQ/view?usp=sharing) is the original JWS archive (without the `logX`/`logY` attributes).

And [here](https://drive.google.com/file/d/0B3aYYo6rNYZhVlZ5RjFFYjF6Rm8/view?usp=sharing) is the modified version where I manually inserted `logX` and `logY`:

**Comment by matthiaskoenig** [comment]
I am running in the same issues.

As I understand SED-ML L1V3 it only contains the changes related to data, but none of the changes related to plots, i.e. logX and logY is not allowed on plot2D in L1V3.

**Comment by fbergmann** [comment]
well, three years ago we actually already a long, long time agreed, that having log attributes on curves makes no sense whatsoever, and instead that it ought to be on the plot. But if this causes issues, then i will make it optional for now. 

BTW ... it is very hard to find a draft document of l1v3 these days :)

**Comment by matthiaskoenig** [comment]
I updated the information on the homepage. You can now directly access the latest draft from:
https://sed-ml.github.io/specifications.html
