### ISSUE TITLE
Numl functions not working with python bindings

### ISSUE THREAD

**Issue by matthiaskoenig** [fbergmann/libSEDML#48]
Hi Frank,
trying to read the numl data with the libsedml python bindings does not work. Somehow the numl related functions are not callable via the python interface, despite them being visible (i.e. I can see the documention and the function via the IDE)
(installed via pip install python-libsedml, version 0.4.1, or via the wheel Kyle build from develop version)

When trying to call functions on the NumlDocument I get:
```
/home/mkoenig/envs/tellurium-py27/bin/python /home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py
Traceback (most recent call last):
  File "/home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py", line 85, in <module>
    df_numl = load_numl_data(SOURCE_NUML)
  File "/home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py", line 63, in load_numl_data
    print(doc_numl.getNumResultComponents())
AttributeError: 'SwigPyObject' object has no attribute 'getNumResultComponents'
Version: 0.4.1
<Swig Object of type 'NUMLDocument_t *' at 0x7f41d6f06de0>
```
Example attached.
[sedmldata.tar.gz](https://github.com/fbergmann/libSEDML/files/1110917/sedmldata.tar.gz)

The best
Matthias

**Comment by fbergmann** [comment]
Hello Matthias,

i’m not entirely sure that the null bits are exposed at all through libsedml … probably not .. it would be better to use the libnuml python library … but i guess that just means there is another bug for me to fix somewhere :)

i’ll look at it first thing in the morning

cheers
Frank

On Jun 28, 2017, at 9:56 PM, Matthias König <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Frank,
trying to read the numl data with the libsedml python bindings does not work. Somehow the numl related functions are not callable via the python interface, despite them being visible (i.e. I can see the documention and the function via the IDE)
(installed via pip install python-libsedml, version 0.4.1, or via the wheel Kyle build from develop version)

When trying to call functions on the NumlDocument I get:

/home/mkoenig/envs/tellurium-py27/bin/python /home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py
Traceback (most recent call last):
  File "/home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py", line 85, in <module>
    df_numl = load_numl_data(SOURCE_NUML)
  File "/home/mkoenig/git/tellurium/tellurium/oven/sedmldata/reading_numl.py", line 63, in load_numl_data
    print(doc_numl.getNumResultComponents())
AttributeError: 'SwigPyObject' object has no attribute 'getNumResultComponents'
Version: 0.4.1
<Swig Object of type 'NUMLDocument_t *' at 0x7f41d6f06de0>


Example attached.
sedmldata.tar.gz<https://github.com/fbergmann/libSEDML/files/1110917/sedmldata.tar.gz>

The best
Matthias

**Comment by matthiaskoenig** [comment]
Hi Frank,

yes, it looks like the libnuml python bindings are not available from within the libsedml python bindings. 
I just tried building libnuml with the python bindings and can now get access to the numl information via this way.
M

**Comment by fbergmann** [comment]
great that was what i was going to suggest :) …

great

Frank


On Jun 28, 2017, at 11:13 PM, Matthias König <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Frank,

yes, it looks like the libnuml python bindings are not available from within the libsedml python bindings.
I just tried building libnuml with the python bindings and can now get access to the numl information via this way.
M

**Comment by matthiaskoenig** [comment]
Posting the full solution here in case anybody needs it:
Install both libsedml and libnuml python packages which makes the numl functions available, i.e.

```
pip install python-libsedml
pip install python-libnuml
```

**Comment by fbergmann** [comment]
this is the same issue as #49 , it will all be sorted at one point when the xml layer is properly extracted. Until then making sure the load order is correct (using reload in the worse case) is the only solution i have.
