### ISSUE TITLE
Update the default version?

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#54]
Right now, the default level and version are 1 and 2 respectively (see [here](https://github.com/fbergmann/libSEDML/blob/master/sedml/SedNamespaces.h#L77)). Yet, the current version of SED-ML is L1V3 and L1V4 is around the corner. So, make sure to update the default version to 4 once L1V4 is out?

**Comment by fbergmann** [comment]
Yes, i plan to update libSEDML over the next 2 weeks. it will be 1.3 for the next version.

**Comment by fbergmann** [comment]
actually before adding the new code i tagged a 0.4.4 with the vesion 3 as default.

**Comment by agarny** [comment]
Just noticed that your tag is `0.4.4` while the previous ones were `v0.4.3`, `v0.4.2`, etc. Clearly no big deal, but thought I would mention it just in case.

**Comment by fbergmann** [comment]
retagged :) thanks
