### ISSUE TITLE
Special L1V4 version of libSEDML: reading a SED-ML file not working as expected!?

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#58]
I am trying to read a valid (L1V2) SED-ML file using `readSedML()` and it all works fine using [version `0.4.4` of libSEDML](https://github.com/fbergmann/libSEDML/releases/tag/v0.4.4), but not using the [special L1V4 version of libSEDML](https://github.com/fbergmann/libSEDML/releases/tag/l1v4-harmony). After the call to `readSedML()`, I get what seems to be a valid `SedDocument` object, but then if I check some of its properties, I can see that `mIsSetLevel`, `mIsSetVersion`, `mLevel` and `mVersion` are set to `false`, `false`, `49` and `40`, respectively while I would have expected `true`, `true`, `1` and `2`, respectively (as is the case using [version `0.4.4` of libSEDML](https://github.com/fbergmann/libSEDML/releases/tag/v0.4.4)). So, not sure what is going wrong here, but this might also explain issue #57?...

**Comment by fbergmann** [comment]
could you please attach or mail me a version of the file you read? That would help in tracking down the issue. the new version is pretty much a replacement of the old one, but my tests seemed to work so far. 

thanks

**Comment by agarny** [comment]
Ok, _mea culpa_, I clearly had a problem of build cache. I was switching between your `0.4.4` and `l1v4-harmony` tags and back, and my build cache clearly got messed up in the process. I have just done a clean build of both tags, and both work as expected. Sorry about that!
