### ISSUE TITLE
Package version vs soname version

### ISSUE THREAD

**Issue by sagitter** [fbergmann/libSEDML#62]
Hi all.

I see a pre-release package jumping from `0.4.4` (like its soname) to a `2.0.6` versioned package that provides soname `0.4.5`

Is it a definitive choice for next releases of libSEDML?
That is, will next versions be all bigger than `2.0.6`?

**Comment by fbergmann** [comment]
the code from the l1v4 branch is a complete replacement from what was there before, thus the version jump. Currently it is a pre-release, as L1v4 has not been finalized yet. I'm not sure where the differences with the  soname comes from, as the property is being set: 

```
if (LIBSEDML_SHARED_VERSION)
  SET_TARGET_PROPERTIES(${LIBSEDML_LIBRARY} PROPERTIES
                        SOVERSION ${LIBSEDML_VERSION_MAJOR}
                        VERSION ${LIBSEDML_VERSION_MAJOR}.${LIBSEDML_VERSION_MINOR}.${LIBSEDML_VERSION_PATCH})
endif()

```

**Comment by fbergmann** [comment]
Thanks for letting me know, that release came out of the wrong branch, this should now be fixed.
