### ISSUE TITLE
L1V4: add SEDML_LINETYPE_DASHDOTDOT as a possible line type

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#64]
Right now, a line type can be:
```
SEDML_LINETYPE_NONE
SEDML_LINETYPE_SOLID
SEDML_LINETYPE_DASH
SEDML_LINETYPE_DOT
SEDML_LINETYPE_DASHDOT
SEDML_LINETYPE_INVALID
```

but, at Harmony, we agreed to add `dashDotDot`, so we should add `SEDML_LINETYPE_DASHDOTDOT` to the above list.

**Comment by fbergmann** [comment]
agreed

**Comment by agarny** [comment]
With the release of v2.0.7, I imagine this issue can be closed?
