### ISSUE TITLE
L1V4: accessing derivatives

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#65]
I don't believe the current L1V4 branch of libSEDML can be used to access derivatives? However, from what we discussed at Harmony 2019:

L1V4 will allow access to additional symbols in simulations. By adding a dependentVariable on Variable derivatives can be accessed.
The additional symbols added are
`urn:sedml:symbol:rateOfChange` (derivative of variable with respect to independent variable, in case of SBML in regard to time, e.g., dS1/dt while in CellML that independent variable can be time, length, etc.)
`urn:sedml:symbol:derivative` (derivative with respect to other variable, e.g., dS1/dp1)
`urn:sedml:symbol:particleNumber`
`urn:sedml:symbol:amount`
`urn:sedml:symbol:concentration`

**Comment by fbergmann** [comment]
this ought to be possible, i'll add an example

**Comment by fbergmann** [comment]
the thing is that the corresponding sections of the spec have not been written by the editors, so handle with care. I've implemented what was in the UML diagram, and now it should be working

**Comment by agarny** [comment]
Thanks a lot @fbergmann. I agree that these features still need to be officially formalised, hence OpenCOR's use of SED-ML L1V4 will only become official when SED-ML L1V4 is.

In the meantime, it would be nice if you could generate a new release that accounts for issues #64, #65 and #66. Thanks in advance.

**Comment by fbergmann** [comment]
I've created a new prerelease version: 

<https://github.com/fbergmann/libSEDML/releases/tag/v2.0.7>

**Comment by agarny** [comment]
Thanks a lot @fbergmann, much appreciated.

**Comment by agarny** [comment]
With the release of v2.0.7, I imagine this issue can be closed?
