### ISSUE TITLE
L1V4: combined solvers

### ISSUE THREAD

**Issue by agarny** [fbergmann/libSEDML#66]
I don't believe this is supported in the L1V4 branch? Yet, from Harmony 2019:

L1V4 will allow to describe complex and combined simulation algorithms via the introduction of recursive algorithmParameters. This will allow to describe complex simulation algorithms.

**Comment by fbergmann** [comment]
This is or should be possible, i'll commit an example.

**Comment by agarny** [comment]
With the release of v2.0.7, I imagine this issue can be closed?
