### ISSUE TITLE
SEDBase::getNamespaces only returns the namespaces declared on the root element

### ISSUE THREAD

**Issue by nickerso** [fbergmann/libSEDML#77]
I'm almost sure this is a discussion we've had before, but when I grab the namespaces (using the python bindings) for use in executing XPath selectors I'm only getting the namespaces declared on the root element of the SED-ML document. This is what the method is documented to do, so that is good.

But it would be more useful to get all the namespaces from the context node up the tree to correctly handle the namespaces in XPath evaluations.

This is not urgent as the work around is simply to make sure all namespaces are defined on the root element of the SED-ML document.

(@fbergmann, I'm sure we talked about this so I might be missing something, or that might have been for the C# library?)

**Comment by fbergmann** [comment]
@nickerso  I think we'd need a different function for that. And it would actually have to also be able to read all the models that are referenced, to grab the namespaces out of them. What with them possibly being remote, goes a bit beyond of the base method here ... 

I could add a utility function that returns namespaces from a given document? But even then, it would not be enough, as we'd also need to add some more (like usually sbml is used with the default prefix, while for SED-ML we use the 'sbml' prefix usually)... 

unless you are really just asking about the ones declared on teh document, of `SedDocument::getNamespaces` does not give you the namespaces that are declared on the root of the SED-ML document, then that'd be a bug.

**Comment by nickerso** [comment]
Yep, happy to have this in a different method if needed.

The XPath expressions should be evaluated using the namespaces defined in the SED-ML document, so wouldn't need to be searching through the model documents or anything.

Essentially, what I'm thinking is that if I define my `xmlns:cellml="htttp://cellml.org...` on, for example, a `variable` element rather than on the root `sedML` element, then the current `getNamespaces()` method won't pick that up for me to use in evaluating the XPath (not a bug as the documentation says that it would not). It would be nice to get that namespace without having to have my own parsed representation of the SED-ML document.

**Comment by fbergmann** [comment]
right ... currently `getNamespaces()` does only return the ones from the document, not from the individual element. I'll look into what i can do to have that returned.

**Comment by fbergmann** [comment]
would that work?

**Comment by nickerso** [comment]
Thanks @fbergmann, that is perfect. I can use this to get what I am after.

Are there any automatically updated python bindings I could grab? ;-)

**Comment by fbergmann** [comment]
there is not, but i can create some later today. Will let you know when its done

**Comment by fbergmann** [comment]
ok, there is a shiny new release on pypi

<https://pypi.org/project/python-libsedml/>

**Comment by nickerso** [comment]
Many thanks @fbergmann, I can confirm that this is working perfectly for me.

In case it is useful, this is how I am using this (please pardon the horrible Python code)

```python
def get_xpath_namespaces(sed_element):
    """
    Get all the XML namespaces for the given SED-ML element as the XPath context.

    :param sed_element: the SED-ML element to define the context for fetching namespaces.
    :return: a dictionary of defined namespaces.
    """
    ns = {}
    current_sed_base = sed_element
    while current_sed_base:
        xmlns = current_sed_base.getElementNamespaces()
        if xmlns:
            for n in range(0, xmlns.getNumNamespaces()):
                prefix = xmlns.getPrefix(n)
                if prefix == '':
                    # we can't use a default namespace in XPath so filter it out...
                    continue
                elif prefix in ns:
                    # existing namespace prefixes should not be changed
                    continue
                else:
                    uri = xmlns.getURI(n)
                    ns[prefix] = uri
        current_sed_base = current_sed_base.getParentSedObject()
    return ns
```
