### ISSUE TITLE
Turn PYTHON_USE_DYNAMIC_LOOKUP  on by default for at least mac builds

### ISSUE THREAD

**Issue by luciansmith** [fbergmann/libSEDML#81]
If PYTHON_USE_DYNAMIC_LOOKUP is not 'on', a mac build that uses python in one place will not work if Python is not in that expected location.  There's no need to *not* turn this on by default.

**Comment by fbergmann** [comment]
according to: 

<https://github.com/fbergmann/libSEDML/blob/level1-version4/src/bindings/python/CMakeLists.txt>

it already is turned on by default.

**Comment by luciansmith** [comment]
Oh, hmm.  I guess maybe I mis-clicked on it or something?  Thanks for checking!
