### ISSUE TITLE
Add 'name' to SedBase.

### ISSUE THREAD

**Issue by luciansmith** [fbergmann/libSEDML#84]
Functions for metaid and id are present in SedBase, but not 'name'.

**Comment by fbergmann** [comment]
so i looked into it and we would have to regenerate and manually merge a lot of files for this. Not something i will get to immediately. Is there a pressing issue, where this is hurting you? If so, adding a virtual function returning an empty string / setting nothing to the base class could be done quickly if needed. that would have about the same effect

**Comment by luciansmith** [comment]
That's actually what I've done for my own copy of the source ;-)  (Though I have it actually setting/getting a member variable.)

I'd be up for working on the merge, if you like.

**Comment by fbergmann** [comment]
this is now in 2.0.18
