### ISSUE TITLE
Failed to create native libs for Linux and Windows

### ISSUE THREAD

**Issue by gmarupilla** [fbergmann/libSEDML#87]
I'm successful in generating `native libs` for the Mac platform and compiled jar file for `java` bindings, but for some reason, java bindings are not getting built even though the build passes with no issues on `Ubuntu`. Is there any chance of releasing native-libs for `Windows` and `Linux` platforms?

**Comment by gmarupilla** [comment]
Working generating for Linux

**Comment by fbergmann** [comment]
Thanks for letting me know, i made sure that the java bindings compile, and have  created a rudimentary build process, that does build binaries on all platforms. You can find the binaries attached. I hope this works for you: 

<https://github.com/fbergmann/libSEDML/actions/runs/425792307>

from now on all runs should have the binaries, including java binaries attached. Please let me know if that works for you.

**Comment by gmarupilla** [comment]
I got the DLL file for windows, it works. Thank you 😊 for native libs.
