### ISSUE TITLE
getNewXML does not return entire the value or raise an error that it isn't returning the entire value

### ISSUE THREAD

**Issue by jonrkarr** [fbergmann/libSEDML#89]
The intended behavior of changeXML is not clear to me. The text and Listing 2.32 of SED-ML specifications suggest this should function similar to a slice method of an array: the (potentially multiple) XML elements that match an XPATH should be replaced by the (potentially multiple) child XML elements of `NewXML`.

Listing 2.32 of the SED-ML L1V3 specifications:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sedML xmlns="http://sed-ml.org/sed-ml/level1/version3" level="1" version="3">
  <listOfModels>
    <model id="model" language="urn:sedml:language:sbml" source="model.xml">
      <listOfChanges>
        <changeXML target="/sbml:sbml/sbml:model/sbml:listOfParameters/sbml:parameter[@id=’V_mT ’]" >
          <newXML>
            <parameter metaid="metaid_0000010" id="V_mT_1" value="0.7" />
            <parameter metaid="metaid_0000050" id="V_mT_2" value="4.6" />
          </newXML>
        </changeXML>
      </listOfChanges>
    </model>
  </listOfModels>
</sedML>
```

However, libSED-ML behaves differently. In the case of Listing 2.32, `getNewXML` returns only the first child of NewXML. The second child isn't returned. 

libSEDML (2.0.13) code:
```python
import libsedml
doc = libsedml.readSedMLFromFile('tests/fixtures/sedml/change-xml.sedml')
if doc.getErrorLog().getNumFailsWithSeverity(libsedml.LIBSEDML_SEV_ERROR):
    raise Exception(doc_sed.getErrorLog().toString())
 model = doc.getModel(0)
change = model.getChange(0)
new_xml = change.getNewXML()
print(new_xml.convertXMLNodeToString(change.getNewXML()))
[1] <parameter metaid="metaid_0000010" id="V_mT_1" value="0.7"/>
```

I think there's a bug here because the specifications and libSED-ML aren't aligned. Since I'm not sure what was intended, I'm not sure exactly what the bug is.
- Is the mistake in the description of ChangeXML in the specifications?
  - NewXML should have just a single child XML node
  - libSED-ML should raise an error when NewXML has multiple children
  - This makes sense to me because AddXML could be used to add additional children
- OR is the the mistake in libSED-ML?
  - getNewXML should a list of child nodes

What is the intended behavior of SED-ML and libSEDML?

**Comment by fbergmann** [comment]
this is indeed a bug, not entirely sure how to fix it yet. When i did implement full xpath processing previously, i used this implementation: 

<https://sourceforge.net/p/libsedml/code/HEAD/tree/trunk/libSedML/ChangeXML.cs>

do i might have to change the underlying representation of newxml to string, that way you would be able to store all the elements in there.

**Comment by jonrkarr** [comment]
Thanks for sharing. Probably makes sense to wait to fix this until there's consensus on the intended behavior.

**Comment by fbergmann** [comment]
actually, this needed to be fixed, as the library was failing to roundtrip these elements, and would lose information. (At the very least the files from the specification should be able to be read and reproduced, and they are now). Luckily the API did not have to be changed for that, writing would have already allowed to add several elements, and reading can now roundtrip those. New version is on pypi.

**Comment by jonrkarr** [comment]
2.0.14 works. I think this can be closed.
