### ISSUE TITLE
SedSubTask should not have methods for getting/setting ids

### ISSUE THREAD

**Issue by jonrkarr** [fbergmann/libSEDML#95]
`sedml:SubTask` (which directly inherits from `SedBase`) does not have an `id` attribute. However, `libsedml.SedSubTask` has `getId`, `setId`, and `isSetId` methods.

The methods should be removed.
- They are not consistent with the SED-ML schema
- libSED-ML neither reads nor writes the `id` attribute to/from files

**Comment by fbergmann** [comment]
for whatever reason, lucian needd id on everything ... and so in l1v4 they will be added everywhere. I'll look into why they are not saved though.

**Comment by matthiaskoenig** [comment]
I think this issue can be closed with the the recent id/name updates.
